project_id = "mhrekppksiekhstnteyu"

[functions.openphone-webhook]
verify_jwt = false

[functions.send-twilio-notification]
verify_jwt = false

[functions.test-twilio-connection]
verify_jwt = false

[functions.manage-integration-credentials]
verify_jwt = false

[functions.invite-client-user]
verify_jwt = true

[functions.create-user]
verify_jwt = false

[functions.send-user-invitation-email]
verify_jwt = false

[functions.notify-new-lead]
verify_jwt = false

[functions.public-lead-capture]
verify_jwt = false

[functions.public-onboarding-response]
verify_jwt = false

[functions.send-client-invitation-email]
verify_jwt = false

[functions.send-service-request-email]
verify_jwt = false

[functions.notify-service-request]
verify_jwt = false

[functions.api-v1]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false
