project_id = "mhrekppksiekhstnteyu"

[functions.openphone-webhook]
verify_jwt = false

[functions.send-twilio-notification]
verify_jwt = true

[functions.test-twilio-connection]
verify_jwt = true

[functions.invite-client-user]
verify_jwt = true

[functions.create-user]
verify_jwt = false

[functions.send-user-invitation-email]
verify_jwt = false

[functions.notify-new-lead]
verify_jwt = false

[functions.public-lead-capture]
verify_jwt = false

[functions.public-onboarding-response]
verify_jwt = false
