import React from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Download, FileText, Table } from 'lucide-react';
import { useBackboneCables } from '@/hooks/useBackboneCables';
import { useDistributionFrames } from '@/hooks/useDistributionFrames';
import { useRiserPathways } from '@/hooks/useRiserPathways';
import { toast } from 'sonner';

interface RiserDiagramPDFExporterProps {
  locationId: string;
  locationName: string;
}

export const RiserDiagramPDFExporter: React.FC<RiserDiagramPDFExporterProps> = ({
  locationId,
  locationName
}) => {
  const { cables } = useBackboneCables(locationId);
  const { frames } = useDistributionFrames(locationId);
  const { pathways } = useRiserPathways(locationId);

  const generatePDF = async (type: 'diagram' | 'cable_schedule' | 'equipment_list' | 'complete') => {
    try {
      // Import jsPDF dynamically
      const { jsPDF } = await import('jspdf');
      const pdf = new jsPDF();
      
      // Header
      pdf.setFontSize(20);
      pdf.text(`Riser Diagram - ${locationName}`, 20, 20);
      
      pdf.setFontSize(12);
      pdf.text(`Generated on: ${new Date().toLocaleDateString()}`, 20, 30);
      
      let yPosition = 50;

      if (type === 'diagram' || type === 'complete') {
        // Riser Diagram Section
        pdf.setFontSize(16);
        pdf.text('Riser Diagram Overview', 20, yPosition);
        yPosition += 15;

        pdf.setFontSize(10);
        pdf.text(`Total Equipment: ${frames.length}`, 20, yPosition);
        yPosition += 8;
        pdf.text(`Cable Runs: ${cables.length}`, 20, yPosition);
        yPosition += 8;
        pdf.text(`Pathways: ${pathways.length}`, 20, yPosition);
        yPosition += 20;
      }

      if (type === 'cable_schedule' || type === 'complete') {
        // Cable Schedule Table
        pdf.setFontSize(14);
        pdf.text('Backbone Cable Schedule', 20, yPosition);
        yPosition += 15;

        pdf.setFontSize(8);
        const headers = ['Label', 'Type', 'From', 'To', 'Capacity', 'Used', 'Status'];
        const colWidths = [25, 20, 30, 30, 20, 20, 25];
        let xPosition = 20;

        // Table headers
        headers.forEach((header, index) => {
          pdf.text(header, xPosition, yPosition);
          xPosition += colWidths[index];
        });
        yPosition += 8;

        // Table data
        cables.forEach(cable => {
          xPosition = 20;
          const row = [
            cable.cable_label,
            cable.cable_type.toUpperCase(),
            `Floor ${cable.origin_floor}`,
            `Floor ${cable.destination_floor}`,
            cable.capacity_total?.toString() || 'N/A',
            cable.capacity_used.toString(),
            cable.capacity_total ? 
              `${((cable.capacity_used / cable.capacity_total) * 100).toFixed(1)}%` : 'N/A'
          ];

          row.forEach((cell, index) => {
            pdf.text(cell, xPosition, yPosition);
            xPosition += colWidths[index];
          });
          yPosition += 6;

          // Start new page if needed
          if (yPosition > 250) {
            pdf.addPage();
            yPosition = 20;
          }
        });
        yPosition += 15;
      }

      if (type === 'equipment_list' || type === 'complete') {
        // Equipment List
        if (yPosition > 200) {
          pdf.addPage();
          yPosition = 20;
        }

        pdf.setFontSize(14);
        pdf.text('Distribution Frame Equipment', 20, yPosition);
        yPosition += 15;

        frames.forEach(frame => {
          pdf.setFontSize(10);
          pdf.text(`${frame.frame_type} - Floor ${frame.floor}`, 20, yPosition);
          yPosition += 8;
          
          pdf.setFontSize(8);
          pdf.text(`  Port Count: ${frame.port_count}`, 25, yPosition);
          yPosition += 6;
          pdf.text(`  Capacity: ${frame.capacity}`, 25, yPosition);
          yPosition += 6;
          
          if (frame.room) {
            pdf.text(`  Location: ${frame.room}`, 25, yPosition);
            yPosition += 6;
          }
          yPosition += 5;

          // Start new page if needed
          if (yPosition > 250) {
            pdf.addPage();
            yPosition = 20;
          }
        });
      }

      // Footer
      const pageCount = pdf.getNumberOfPages();
      for (let i = 1; i <= pageCount; i++) {
        pdf.setPage(i);
        pdf.setFontSize(8);
        pdf.text(`Page ${i} of ${pageCount}`, 180, 285);
        pdf.text('Generated by Port Atlas', 20, 285);
      }

      // Download the PDF
      const filename = `${locationName.replace(/\s+/g, '_')}_${type}_${new Date().toISOString().split('T')[0]}.pdf`;
      pdf.save(filename);
      
      toast.success(`${type.replace('_', ' ')} PDF exported successfully`);
    } catch (error) {
      console.error('Error generating PDF:', error);
      toast.error('Failed to generate PDF');
    }
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <FileText className="h-5 w-5" />
          Export Documentation
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="grid grid-cols-2 gap-4">
          <Button 
            variant="outline" 
            className="flex items-center gap-2"
            onClick={() => generatePDF('diagram')}
          >
            <Download className="h-4 w-4" />
            Riser Diagram
          </Button>
          
          <Button 
            variant="outline" 
            className="flex items-center gap-2"
            onClick={() => generatePDF('cable_schedule')}
          >
            <Table className="h-4 w-4" />
            Cable Schedule
          </Button>
          
          <Button 
            variant="outline" 
            className="flex items-center gap-2"
            onClick={() => generatePDF('equipment_list')}
          >
            <FileText className="h-4 w-4" />
            Equipment List
          </Button>
          
          <Button 
            className="flex items-center gap-2"
            onClick={() => generatePDF('complete')}
          >
            <Download className="h-4 w-4" />
            Complete Report
          </Button>
        </div>

        <div className="space-y-2">
          <h4 className="text-sm font-medium">Export Options</h4>
          <div className="flex flex-wrap gap-2">
            <Badge variant="outline">Professional PDF Format</Badge>
            <Badge variant="outline">TIA-606 Compliant</Badge>
            <Badge variant="outline">As-Built Documentation</Badge>
            <Badge variant="outline">Cable Schedules</Badge>
          </div>
        </div>

        <div className="text-xs text-muted-foreground">
          <p>Generated PDFs include:</p>
          <ul className="list-disc ml-4 space-y-1">
            <li>Professional header with project information</li>
            <li>Equipment specifications and locations</li>
            <li>Cable run details with capacity utilization</li>
            <li>Pathway information and fire stop locations</li>
            <li>TIA-606 compliant labeling and documentation</li>
          </ul>
        </div>
      </CardContent>
    </Card>
  );
};