-- ============================================
-- Add organization_id columns and indexes
-- ============================================

ALTER TABLE public.daily_logs ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.supplier_catalogs ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.supplier_price_history ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.procurement_settings ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.procurement_approvals ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.stock_transactions ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.service_plans ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.subscription_billing ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.maintenance_schedules ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.employee_schedules ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.employee_availability ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.schedule_templates ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.safety_checklists ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.safety_checklist_items ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.safety_checklist_submissions ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.safety_incidents ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.quality_checklists ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.quality_checklist_items ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.quality_checklist_submissions ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.signatures ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.drop_points ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.drop_point_photos ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.backbone_cables ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.cable_segments ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.cable_connections ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.cable_junction_boxes ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.distribution_frames ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.network_devices ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.device_ports ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.patch_connections ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.vlans ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.port_vlan_assignments ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.racks ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.riser_pathways ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.room_views ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.room_view_photos ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.canvas_drawings ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.documentation_files ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.capacity_alerts ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.customer_notes ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.user_activity_log ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.user_roles ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.tool_checkouts ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.chat_rooms ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.chat_messages ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.chat_participants ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.notification_templates ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.openphone_call_logs ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.system_configurations ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.workflow_configurations ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.twilio_settings ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.business_rules ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.dropdown_options ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.change_logs ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.test_results ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.test_results_files ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.walk_through_notes ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.purchase_order_items ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.sync_queue ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_daily_logs_org ON public.daily_logs(organization_id);
CREATE INDEX IF NOT EXISTS idx_supplier_catalogs_org ON public.supplier_catalogs(organization_id);
CREATE INDEX IF NOT EXISTS idx_service_plans_org ON public.service_plans(organization_id);
CREATE INDEX IF NOT EXISTS idx_maintenance_schedules_org ON public.maintenance_schedules(organization_id);
CREATE INDEX IF NOT EXISTS idx_employee_schedules_org ON public.employee_schedules(organization_id);
CREATE INDEX IF NOT EXISTS idx_employee_availability_org ON public.employee_availability(organization_id);
CREATE INDEX IF NOT EXISTS idx_safety_checklists_org ON public.safety_checklists(organization_id);
CREATE INDEX IF NOT EXISTS idx_quality_checklists_org ON public.quality_checklists(organization_id);
CREATE INDEX IF NOT EXISTS idx_drop_points_org ON public.drop_points(organization_id);
CREATE INDEX IF NOT EXISTS idx_backbone_cables_org ON public.backbone_cables(organization_id);
CREATE INDEX IF NOT EXISTS idx_distribution_frames_org ON public.distribution_frames(organization_id);
CREATE INDEX IF NOT EXISTS idx_network_devices_org ON public.network_devices(organization_id);
CREATE INDEX IF NOT EXISTS idx_vlans_org ON public.vlans(organization_id);
CREATE INDEX IF NOT EXISTS idx_racks_org ON public.racks(organization_id);
CREATE INDEX IF NOT EXISTS idx_chat_rooms_org ON public.chat_rooms(organization_id);
CREATE INDEX IF NOT EXISTS idx_system_configurations_org ON public.system_configurations(organization_id);
CREATE INDEX IF NOT EXISTS idx_twilio_settings_org ON public.twilio_settings(organization_id);
CREATE INDEX IF NOT EXISTS idx_dropdown_options_org ON public.dropdown_options(organization_id);

-- Enable RLS and create policies for key tables
ALTER TABLE public.daily_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employee_schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employee_availability ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.safety_checklists ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quality_checklists ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.drop_points ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.backbone_cables ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.distribution_frames ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.network_devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vlans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.racks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_configurations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.twilio_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dropdown_options ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.maintenance_schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.service_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customer_notes ENABLE ROW LEVEL SECURITY;

-- Create org isolation policies
CREATE POLICY "org_isolation_daily_logs" ON public.daily_logs FOR ALL USING (public.is_super_admin(auth.uid()) OR organization_id IN (SELECT public.get_user_organizations(auth.uid())) OR organization_id IS NULL);
CREATE POLICY "org_isolation_employee_schedules" ON public.employee_schedules FOR ALL USING (public.is_super_admin(auth.uid()) OR organization_id IN (SELECT public.get_user_organizations(auth.uid())) OR organization_id IS NULL);
CREATE POLICY "org_isolation_employee_availability" ON public.employee_availability FOR ALL USING (public.is_super_admin(auth.uid()) OR organization_id IN (SELECT public.get_user_organizations(auth.uid())) OR organization_id IS NULL);
CREATE POLICY "org_isolation_safety_checklists" ON public.safety_checklists FOR ALL USING (public.is_super_admin(auth.uid()) OR organization_id IN (SELECT public.get_user_organizations(auth.uid())) OR organization_id IS NULL);
CREATE POLICY "org_isolation_quality_checklists" ON public.quality_checklists FOR ALL USING (public.is_super_admin(auth.uid()) OR organization_id IN (SELECT public.get_user_organizations(auth.uid())) OR organization_id IS NULL);
CREATE POLICY "org_isolation_drop_points" ON public.drop_points FOR ALL USING (public.is_super_admin(auth.uid()) OR organization_id IN (SELECT public.get_user_organizations(auth.uid())) OR organization_id IS NULL);
CREATE POLICY "org_isolation_backbone_cables" ON public.backbone_cables FOR ALL USING (public.is_super_admin(auth.uid()) OR organization_id IN (SELECT public.get_user_organizations(auth.uid())) OR organization_id IS NULL);
CREATE POLICY "org_isolation_distribution_frames" ON public.distribution_frames FOR ALL USING (public.is_super_admin(auth.uid()) OR organization_id IN (SELECT public.get_user_organizations(auth.uid())) OR organization_id IS NULL);
CREATE POLICY "org_isolation_network_devices" ON public.network_devices FOR ALL USING (public.is_super_admin(auth.uid()) OR organization_id IN (SELECT public.get_user_organizations(auth.uid())) OR organization_id IS NULL);
CREATE POLICY "org_isolation_vlans" ON public.vlans FOR ALL USING (public.is_super_admin(auth.uid()) OR organization_id IN (SELECT public.get_user_organizations(auth.uid())) OR organization_id IS NULL);
CREATE POLICY "org_isolation_racks" ON public.racks FOR ALL USING (public.is_super_admin(auth.uid()) OR organization_id IN (SELECT public.get_user_organizations(auth.uid())) OR organization_id IS NULL);
CREATE POLICY "org_isolation_chat_rooms" ON public.chat_rooms FOR ALL USING (public.is_super_admin(auth.uid()) OR organization_id IN (SELECT public.get_user_organizations(auth.uid())) OR organization_id IS NULL);
CREATE POLICY "org_isolation_system_configurations" ON public.system_configurations FOR ALL USING (public.is_super_admin(auth.uid()) OR organization_id IN (SELECT public.get_user_organizations(auth.uid())) OR organization_id IS NULL);
CREATE POLICY "org_isolation_twilio_settings" ON public.twilio_settings FOR ALL USING (public.is_super_admin(auth.uid()) OR organization_id IN (SELECT public.get_user_organizations(auth.uid())) OR organization_id IS NULL);
CREATE POLICY "org_isolation_dropdown_options" ON public.dropdown_options FOR ALL USING (public.is_super_admin(auth.uid()) OR organization_id IN (SELECT public.get_user_organizations(auth.uid())) OR organization_id IS NULL);
CREATE POLICY "org_isolation_maintenance_schedules" ON public.maintenance_schedules FOR ALL USING (public.is_super_admin(auth.uid()) OR organization_id IN (SELECT public.get_user_organizations(auth.uid())) OR organization_id IS NULL);
CREATE POLICY "org_isolation_service_plans" ON public.service_plans FOR ALL USING (public.is_super_admin(auth.uid()) OR organization_id IN (SELECT public.get_user_organizations(auth.uid())) OR organization_id IS NULL);
CREATE POLICY "org_isolation_customer_notes" ON public.customer_notes FOR ALL USING (public.is_super_admin(auth.uid()) OR organization_id IN (SELECT public.get_user_organizations(auth.uid())) OR organization_id IS NULL);