// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhrekppksiekhstnteyu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ocmVrcHBrc2lla2hzdG50ZXl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NTE5NTMsImV4cCI6MjA3MzQyNzk1M30.7gq7z8aPz0BK-_G1ALNSolHaDNB-6kx1hSzE68K6ZeY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});